version: '2'
services:
    angulared-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/angularEd/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=angularEd
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
